[project]
name = "codemayhem-api"
revision = "1.0"

[profiles.university]
SURREALDB_HOST.description = "SurrealKit database host URL"
SURREALDB_NAME.description = "SurrealKit database name"
SURREALDB_NAMESPACE.description = "SurrealKit database namespace"
SURREALDB_PASSWORD.description = "SurrealKit database password"
SURREALDB_USER.description = "SurrealKit database user"
